baseURL = 'https://A1gerNoNO.github.io/'
locale = 'zh-cn'
title = 'A1gerNoNO'
theme = 'PaperMod'

copyright = 'Copyright &copy; 2026 A1gerNoNO'
hasCJKLanguage = true
enableRobotsTXT = true

[permalinks]
  posts = '/posts/:year/:month/:slug/'

[params]
  env = 'production'
  description = 'A1gerNoNO 的技术博客'
  defaultTheme = 'auto'
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  comments = false
  hideFooter = false

  [params.homeInfoParams]
    Title = 'A1gerNoNO'
    Content = '技术博客'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    name = '文章'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = '关于'
    url = '/about/'
    weight = 2
